core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform
